# docker-compose.yml
version: "3"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=glee
    ports:
      - "5533:5432"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8084:8080
    
